import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import 'slick-carousel/slick/slick.css';
import 'slick-carousel/slick/slick-theme.css';
import Navbar from "@/Components/Common/Navbar";



const PoppinsFont = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400","500", "600"],
});

export const metadata: Metadata = {
  title: "Dobby",
  description: "Generated by Dobby",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={PoppinsFont.className}>
      <Navbar />
        {children}
        </body>
      
    </html>
  );
}
